@startuml
skinparam style strictuml
hide footbox

participant Ex1.class as Ex1
participant Year.class as Year
participant "year: Year" as year

[o-> Ex1 : main(args)
Ex1->Year ++ : parse()
Year -> year : <<Create>> Year()
return year

Ex1 -> year ++ : getValue()
return val

loop
    Ex1->Ex1 : val = val + 1
    Ex1->Year ++ : of(val)
    Year->Year ++ : isLeap()
    return true or false
    return leap
break leap = true
end break
end loop

[o<- Ex1 : println(val)

@enduml